name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: terraform-test
        run: echo -e "Check up the quality of code"

  terraform:
    needs: build
    uses: ./.github/workflows/terraform.yml


